version: '3.9'

services:
  scheduleapp.api:
    image: scheduleapp.api
    build:
      context: .
      dockerfile: ScheduleApp.API/Dockerfile
    ports:
      - "8181:8181"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      JWT_KEY: "${JWT_KEY}"
      JWT_ISSUER: "MiniApp"
      JWT_AUDIENCE: "MiniApp"
    labels:
      - traefik.enable=true
      - traefik.http.routers.reviewanalyzer.rule=Host(`api.schedule.mixdev.me`)
      - traefik.http.routers.reviewanalyzer.entrypoints=https
      - traefik.http.routers.reviewanalyzer.tls.certresolver=letsencrypt

  client:
    build:
      context: ../miniapp
      dockerfile: Dockerfile
    depends_on:
      - scheduleapp.api
    ports:
      - "5173:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.reviewanalyzer.rule=Host(`schedule.mixdev.me`)
      - traefik.http.routers.reviewanalyzer.entrypoints=https
      - traefik.http.routers.reviewanalyzer.tls.certresolver=letsencrypt