version: "3.9"

services:
  scheduleapp-api:
    container_name: scheduleapp-api
    build:
      context: .
      dockerfile: ScheduleApp.API/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      JWT_KEY: "${JWT_KEY}"
      JWT_ISSUER: "MiniApp"
      JWT_AUDIENCE: "MiniApp"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.scheduleapp-api.rule=Host(`api.schedule.mixdev.me`)
      - traefik.http.routers.scheduleapp-api.entrypoints=https
      - traefik.http.routers.scheduleapp-api.tls.certresolver=letsencrypt
      - traefik.http.services.scheduleapp-api.loadbalancer.server.port=8080
      - 

  client:
    build:
      context: ../miniapp
      dockerfile: Dockerfile
    depends_on:
      - scheduleapp.api
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`schedule.mixdev.me`)
      - traefik.http.routers.client.entrypoints=https
      - traefik.http.routers.client.tls.certresolver=letsencrypt
      - traefik.http.services.client.loadbalancer.server.port=80