// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScheduleApp.PostgreSql;

#nullable disable

namespace ScheduleApp.PostgreSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.DayOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("End")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDayOff")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("SlotDuration")
                        .HasColumnType("interval");

                    b.Property<TimeOnly?>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("WeeklyScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("Overrides");
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.DaySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDayOff")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("SlotDuration")
                        .HasColumnType("interval");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("WeeklyScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("DaySchedules");
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DayScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayScheduleId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.WeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.DayOverride", b =>
                {
                    b.HasOne("ScheduleApp.Core.Model.Scheduling.WeeklySchedule", null)
                        .WithMany("Overrides")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.DaySchedule", b =>
                {
                    b.HasOne("ScheduleApp.Core.Model.Scheduling.WeeklySchedule", null)
                        .WithMany("DaySchedules")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.Slot", b =>
                {
                    b.HasOne("ScheduleApp.Core.Model.Scheduling.DaySchedule", null)
                        .WithMany("DaySlots")
                        .HasForeignKey("DayScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.DaySchedule", b =>
                {
                    b.Navigation("DaySlots");
                });

            modelBuilder.Entity("ScheduleApp.Core.Model.Scheduling.WeeklySchedule", b =>
                {
                    b.Navigation("DaySchedules");

                    b.Navigation("Overrides");
                });
#pragma warning restore 612, 618
        }
    }
}
